import { afterEach, beforeAll, beforeEach, describe, expect, it } from "bun:test";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import type { ToolSession } from "@oh-my-pi/pi-coding-agent/tools";
import { WriteTool } from "@oh-my-pi/pi-coding-agent/tools/write";

function createSession(cwd: string): ToolSession {
	return {
		cwd,
		hasUI: false,
		getSessionFile: () => path.join(cwd, "session.jsonl"),
		getSessionSpawns: () => "*",
		getArtifactsDir: () => path.join(cwd, "artifacts"),
		allocateOutputArtifact: async () => ({ id: "artifact-1", path: path.join(cwd, "artifact-1.log") }),
		settings: Settings.isolated({ "edit.blockAutoGenerated": false, "edit.mode": "replace" }),
		enableLsp: false,
	};
}

describe("write tool read projection guard", () => {
	let tmpDir: string;

	beforeAll(async () => {
		await Settings.init({ inMemory: true });
	});

	beforeEach(async () => {
		tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "write-read-projection-test-"));
	});

	afterEach(async () => {
		await fs.rm(tmpDir, { recursive: true, force: true });
	});

	it.each([
		{
			name: "Showing lines notice",
			totalLines: 60,
			visibleLines: 20,
			notice: "[Showing lines 1-20 of 60. Use :21 to continue]",
		},
		{
			name: "remaining-lines notice",
			totalLines: 60,
			visibleLines: 20,
			notice: "[40 more lines in file. Use :21 to continue]",
		},
		{
			name: "summary elision notice",
			totalLines: 40,
			visibleLines: 10,
			notice: "[…30ln elided; re-read needed ranges with sample.txt:11-40]",
		},
	])("rejects an exact $name projection without changing the file", async ({ totalLines, visibleLines, notice }) => {
		const filePath = path.join(tmpDir, "sample.txt");
		const originalLines = Array.from({ length: totalLines }, (_, index) => `line ${index + 1}`);
		const original = `${originalLines.join("\n")}\n`;
		await Bun.write(filePath, original);
		const partial = `${originalLines.slice(0, visibleLines).join("\n")}\n${notice}\n`;

		await expect(
			new WriteTool(createSession(tmpDir)).execute("call-1", { path: filePath, content: partial }),
		).rejects.toThrow(`covers only ${visibleLines} of ${totalLines} lines`);
		expect(await Bun.file(filePath).text()).toBe(original);
	});

	it("writes a literal read notice when it is not replacing an existing projection source", async () => {
		const filePath = path.join(tmpDir, "documentation.txt");
		const content = "Example omp output:\n[Showing lines 1-20 of 60. Use :21 to continue]\n";

		await new WriteTool(createSession(tmpDir)).execute("call-2", { path: filePath, content });

		expect(await Bun.file(filePath).text()).toBe(content);
	});
});
